-- ============================================================================
-- DUGSI PRO 2026 - MIGRATION 01: CORE TABLES (1-8)
-- ============================================================================

-- 1. Users Table
CREATE TABLE IF NOT EXISTS dugsiga_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  verified BOOLEAN DEFAULT TRUE,
  verification_code TEXT,
  role TEXT DEFAULT 'admin',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Students Table
CREATE TABLE IF NOT EXISTS dugsiga_students (
  id TEXT PRIMARY KEY,
  school_id TEXT NOT NULL,
  full_name TEXT NOT NULL,
  class TEXT NOT NULL,
  gender TEXT NOT NULL,
  guardian_phone TEXT NOT NULL,
  status TEXT DEFAULT 'active',
  photo TEXT,
  date_of_birth TEXT,
  address TEXT,
  guardian_name TEXT,
  section TEXT,
  roll_number TEXT,
  created_at TEXT
);

-- 3. Classes Table
CREATE TABLE IF NOT EXISTS dugsiga_classes (
  id TEXT PRIMARY KEY,
  school_id TEXT NOT NULL,
  class_name TEXT NOT NULL,
  teacher_name TEXT,
  room_number TEXT,
  description TEXT,
  section TEXT,
  capacity INTEGER DEFAULT 30,
  academic_year TEXT DEFAULT '2026-2027',
  status TEXT DEFAULT 'active',
  created_at TEXT
);

-- 4. Subjects Table
CREATE TABLE IF NOT EXISTS dugsiga_subjects (
  id TEXT PRIMARY KEY,
  school_id TEXT NOT NULL,
  subject_name TEXT NOT NULL,
  subject_code TEXT,
  class_name TEXT,
  teacher_name TEXT,
  category TEXT,
  description TEXT,
  pass_marks NUMERIC DEFAULT 50,
  max_marks NUMERIC DEFAULT 100,
  status TEXT DEFAULT 'active',
  created_at TEXT
);

-- 5. Exam Scores Table
CREATE TABLE IF NOT EXISTS dugsiga_exam_scores (
  id TEXT PRIMARY KEY,
  school_id TEXT NOT NULL,
  student_id TEXT NOT NULL,
  student_name TEXT,
  class_name TEXT NOT NULL,
  subject_name TEXT NOT NULL,
  exam_name TEXT NOT NULL,
  term TEXT DEFAULT 'Term 1',
  max_marks NUMERIC DEFAULT 100,
  marks_obtained NUMERIC NOT NULL,
  grade TEXT,
  exam_date TEXT,
  created_at TEXT
);

-- 6. Student Attendance Table
CREATE TABLE IF NOT EXISTS dugsiga_attendance (
  school_id TEXT NOT NULL,
  date TEXT NOT NULL,
  student_id TEXT NOT NULL,
  status TEXT NOT NULL,
  timestamp TEXT,
  session_type TEXT DEFAULT 'before_break',
  PRIMARY KEY (school_id, date, student_id, session_type)
);

-- 7. Legacy Monthly Fees Table
CREATE TABLE IF NOT EXISTS dugsiga_fees (
  id TEXT PRIMARY KEY,
  school_id TEXT NOT NULL,
  student_id TEXT NOT NULL,
  month TEXT NOT NULL,
  year INTEGER NOT NULL,
  amount NUMERIC NOT NULL,
  paid_amount NUMERIC NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'unpaid',
  created_at TEXT,
  updated_at TEXT,
  history JSONB DEFAULT '[]'::jsonb
);

-- 8. School Settings Table
CREATE TABLE IF NOT EXISTS dugsiga_settings (
  school_id TEXT NOT NULL,
  key TEXT NOT NULL,
  value JSONB,
  PRIMARY KEY (school_id, key)
);
